from models.database import db
from sqlalchemy.orm import Mapped, mapped_column


class Grades(db.Model):
    __tablename__ = "grades"
    seq: Mapped[int] = mapped_column(primary_key=True)
    batch: Mapped[int] = mapped_column(nullable=False)
    TOTAL: Mapped[int] = mapped_column(default=0)
    SEM9: Mapped[int] = mapped_column(default=0)
    SEM8: Mapped[int] = mapped_column(default=0)
    SEM7: Mapped[int] = mapped_column(default=0)
    SEM6: Mapped[int] = mapped_column(default=0)
    SEM5: Mapped[int] = mapped_column(default=0)
    SEM4: Mapped[int] = mapped_column(default=0)
    SEM3: Mapped[int] = mapped_column(default=0)
    SEM2: Mapped[int] = mapped_column(default=0)
    SEM1: Mapped[int] = mapped_column(default=0)
    EBMR: Mapped[int] = mapped_column(default=0)
    ENT: Mapped[int] = mapped_column(default=0)
    FMIMC: Mapped[int] = mapped_column(default=0)
    OPTH: Mapped[int] = mapped_column(default=0)
    OGYN2: Mapped[int] = mapped_column(default=0)
    PED2: Mapped[int] = mapped_column(default=0)
    MED3: Mapped[int] = mapped_column(default=0)
    SURG3: Mapped[int] = mapped_column(default=0)
    surg2: Mapped[int] = mapped_column(default=0)
    MED2: Mapped[int] = mapped_column(default=0)
    PED1: Mapped[int] = mapped_column(default=0)
    OGYN1: Mapped[int] = mapped_column(default=0)
    COM: Mapped[int] = mapped_column(default=0)
    SURG1: Mapped[int] = mapped_column(default=0)
    MED1: Mapped[int] = mapped_column(default=0)
    FCT: Mapped[int] = mapped_column(default=0)
    RLM: Mapped[int] = mapped_column(default=0)
    DERM: Mapped[int] = mapped_column(default=0)
    PSYC: Mapped[int] = mapped_column(default=0)
    BMSP: Mapped[int] = mapped_column(default=0)
    _1104: Mapped[int] = mapped_column(default=0)
    _1103: Mapped[int] = mapped_column(default=0)
    _1102: Mapped[int] = mapped_column(default=0)
    _1101: Mapped[int] = mapped_column(default=0)
